### ISSUE TITLE
livedown doesn't detect / refresh changes after first file update

### ISSUE THREAD

**Issue by amontalenti** [shime/livedown#16]
I have a small nuisance of an issue. I use livedown with vim-livedown on Ubuntu 14.04. I have version 1.0.8 installed. Though livedown opens on my Markdown file fine and shows it in a browser window, it only live-refreshes the browser window upon the first change to the file. Every change after the first does not live-refresh the browser, but instead requires me to refresh my browser window. That said, once manually refreshed, the changes on-disk are reflected. Let me know if there is any way I can provide more debugging information for this.

**Comment by amontalenti** [comment]
FWIW, this is still an issue for me. Not sure what's up with this. How can I help debug it?

**Comment by shime** [comment]
That sucks. Any errors in the browser's console?

**Comment by niftylettuce** [comment]
@amontalenti what does your vim config look like for this?  do you still use this?

**Comment by amontalenti** [comment]
@shime @niftylettuce I'm running shime/vim-livedown at commit e2ea003. I just upgraded livedown using `npm install -g livedown`. After this upgrade, this issue seems to resolved. Closing this issue.

**Comment by phcerdan** [comment]
Umm, I am hitting exactly the same issue.

It refreshes the browser only after the first write. Then nothing.
