### ISSUE TITLE
Relative links to other markdown files

### ISSUE THREAD

**Issue by alex-e-leon** [shime/livedown#17]
@shime Thoughts on adding support for relative links to other markdown files in the same base directory?

**Comment by shime** [comment]
that's what Github does, so it's a good idea to support it

**Comment by hk0i** [comment]
I just ran into the same thing for the first time. Is there any plan for this?

**Comment by ppwwyyxx** [comment]
Yes, support relative links to images would be very helpful as well.

**Comment by niftylettuce** [comment]
DONE! see #32 - try out v2.1.0!  `npm install -g livedown@latest`
