### ISSUE TITLE
"livedown stop" is not working

### ISSUE THREAD

**Issue by shubhamshuklaer** [shime/livedown#19]
I start livedown as `livedown start PATH` and stop as `livedown stop`, but the server isn't stopped. Even when using verbose the there is no error shown. I have to either do ctrl+c on `livedown start PATH` or kill using process id. This is a problem when using livedown vim plugin as I cannot do ctrl+c. For vim `:livedownKill` does nothing just as `livedown stop`.
PS: Thanks for the awesome application.

**Comment by hpurmann** [comment]
For me, it works (both on console and with vim plugin). Running on MacOS, node 6.2.2, livedown 1.0.8.

I get a big node stack trace though:
```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x268b6d2c9e59 <JS Object>#0#
....
```

**Comment by shime** [comment]
It would help a lot if you provided more info about your environment so I can reproduce.

**Comment by shubhamshuklaer** [comment]
Hey sorry about that. I have changed my os since then, so cannot help there. I am closing this issue  as I don't have more info right now.
