### ISSUE TITLE
highlight.js outdated

### ISSUE THREAD

**Issue by caedn** [shime/livedown#26]
`highlight.min.js` (everything in `/vendor` really) is 2 years old which means there is no syntax highlighting for Rust and [many](https://github.com/isagalaev/highlight.js/blob/master/CHANGES.md) other languages.

**Comment by niftylettuce** [comment]
@caedn can you submit a pull request to fix this?

**Comment by rattletat** [comment]
@niftylettuce Can you check whether this is again true? I have some problems highlighting Julia code. Thanks for your work!

**Comment by niftylettuce** [comment]
Can you please check into this more on your end?  You can fork the repo, npm locally link it, upgrade hljs in it if necessary, and see if that fixes?  If it's a problem you have you should be able to learn how to resolve it.  It's not healthy for open source for a single person to be the point of failure and knowledge.

**Comment by rattletat** [comment]
@niftylettuce Thanks for the fast response! I'm not really familiar with javascript package building but I will try to look into it and investigate further :)
