### ISSUE TITLE
Bootstrap call from emacs

### ISSUE THREAD

**Issue by JuanPabloMF** [shime/livedown#37]
Livedown is working well from my emacs client, but this kind of code doesn't render:

    <div class="alert alert-warning">
    You can use an alert to highlight something you want to stand out.
    </div> 

Any way to get bootstrap elements rendered?

**Comment by shime** [comment]
Nope, we follow Github's styling and try to copy it as close as possible. Since this is not supported on Github, it's not gonna be supported in Livedown.

Sorry.
