### ISSUE TITLE
Propose: support directory as path

### ISSUE THREAD

**Issue by imcuttle** [shime/livedown#45]
livedown is awesome!

In my screen, I have a lots of markdown files in same directory, the file struct below:
```text
README.md
   docs/
      readme.md
      foo.md
```

I expect livedown should works with the experience:
1. Run `livedown start --open` or `livedown --open` is same with `livedown start . --open`
2. Open `http://localhost:{port}` rendering `README.md` by default browser
3. I could preview and live edit `docs/foo.md` by url `http://localhost:{port}/docs/foo.md`
    - I could preview and live edit `docs/readme.md` by url `http://localhost:{port}/docs/` too.

livedown support a single markdown file now, I'd like to PR.

**Comment by shime** [comment]
That's a good idea, I would accept a PR that would add this functionality assuming everything was covered with tests.

**Comment by imcuttle** [comment]
Hi, @shime , 😢I implemented it in [live-markd](https://github.com/imcuttle/live-markd) (github favorite markdown preview with live rendering)
